{
 "title": "Hyperledger Fabric Orderer Dash Board",
 "time": { "from": "2021-03-27T09:55:41.632Z", "to": "2021-03-27T10:02:27.700Z" },
 "panels": [
  { "title": "Orderer", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "cluster_comm_egress",
   "type": "bargauge",
   "gridPos": { "h": 4, "w": 24, "x": 0, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "cluster_comm_egress_queue_capacity"
    },
    {
     "expr": "cluster_comm_egress_queue_length"
    },
    {
     "expr": "cluster_comm_egress_queue_workers"
    },
    {
     "expr": "cluster_comm_egress_stream_count"
    },
    {
     "expr": "cluster_comm_egress_tls_connection_count"
    },
    {
     "expr": "cluster_comm_ingress_stream_count"
    }
   ]
  },
  {
   "title": "consensus_etcdraft_proposals",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 5 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "rate(consensus_etcdraft_normal_proposals_received[5m])"
    },
    {
     "expr": "rate(consensus_etcdraft_proposal_failures[5m])"
    }
   ]
  },
  {
   "title": "deliver_blocks",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 5 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    { "expr": "rate(deliver_blocks_sent[5m])" },
    {
     "expr": "rate(deliver_requests_completed[5m])"
    },
    {
     "expr": "rate(deliver_requests_received[5m])"
    },
    {
     "expr": "rate(deliver_streams_closed[5m])"
    },
    {
     "expr": "rate(deliver_streams_opened[5m])"
    }
   ]
  },
  {
   "title": "consensus_etcdraft",
   "type": "gauge",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 13 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "consensus_etcdraft_active_nodes"
    },
    {
     "expr": "consensus_etcdraft_cluster_size"
    },
    {
     "expr": "consensus_etcdraft_committed_block_number"
    },
    {
     "expr": "consensus_etcdraft_config_proposals_received"
    },
    { "expr": "consensus_etcdraft_is_leader" },
    {
     "expr": "consensus_etcdraft_leader_changes"
    },
    {
     "expr": "consensus_etcdraft_normal_proposals_received"
    },
    {
     "expr": "consensus_etcdraft_proposal_failures"
    },
    {
     "expr": "consensus_etcdraft_snapshot_block_number"
    }
   ]
  },
  {
   "title": "cluster_comm_msg_dropped_count",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 22 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "cluster_comm_msg_dropped_count" }
   ]
  },
  {
   "title": "broadcast_processed_count",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 22 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "broadcast_processed_count" }
   ]
  },
  {
   "title": "cluster_comm_msg_send_time\t",
   "type": "heatmap",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 30 },
   "targets": [
    {
     "expr": "  histogram_quantile(0.95, sum(rate(cluster_comm_msg_send_time_bucket[5m])) by (le))"
    }
   ]
  },
  {
   "title": "broadcast_enqueue_duration",
   "type": "heatmap",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 30 },
   "targets": [
    {
     "expr": "histogram_quantile(0.95, sum(rate(broadcast_enqueue_duration_bucket[30s])) by (le))",
     "legendFormat": "{{le}}"
    }
   ]
  },
  {
   "title": "blockcutter_block_fill_duration",
   "type": "heatmap",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 38 },
   "targets": [
    {
     "expr": "blockcutter_block_fill_duration_bucket",
     "legendFormat": "{{le}}"
    }
   ]
  },
  {
   "title": "broadcast_validate_duration",
   "type": "heatmap",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 38 },
   "targets": [
    {
     "expr": "broadcast_validate_duration_bucket",
     "legendFormat": "{{le}}"
    }
   ]
  },
  {
   "title": "ledger_blockstorage_commit_time",
   "type": "heatmap",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 46 },
   "targets": [
    {
     "expr": "ledger_blockstorage_commit_time_bucket",
     "legendFormat": "{{le}}"
    }
   ]
  }
 ]
}