{
 "title": "Hyperledger Fabric Peer Dash Board",
 "time": { "from": "now-5m", "to": "now" },
 "refresh": "5s",
 "panels": [
  { "title": "Peer General", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "ledger_transaction_count",
   "type": "gauge",
   "gridPos": { "h": 6, "w": 24, "x": 0, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "ledger_transaction_count" }
   ]
  },
  {
   "title": "deliver",
   "type": "gauge",
   "gridPos": { "h": 10, "w": 24, "x": 0, "y": 7 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "deliver_blocks_sent" },
    { "expr": "deliver_requests_completed" },
    { "expr": "deliver_requests_received" },
    { "expr": "deliver_streams_closed" },
    { "expr": "deliver_streams_opened" }
   ]
  },
  {
   "title": "gossip_leader_election_leader",
   "type": "stat",
   "gridPos": { "h": 4, "w": 24, "x": 0, "y": 17 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "gossip_leader_election_leader" },
    {
     "expr": "gossip_membership_total_peers_known"
    },
    { "expr": "gossip_payload_buffer_size" }
   ]
  },
  {
   "title": "dockercontroller_chaincode_container_build_duration",
   "type": "heatmap",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 21 },
   "targets": [
    {
     "expr": "dockercontroller_chaincode_container_build_duration_bucket",
     "legendFormat": "{{le}}"
    }
   ]
  },
  { "title": "Chaincode", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 29 } },
  {
   "title": "chaincode_execute",
   "type": "graph",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 30 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "rate(chaincode_execute_timeouts[5m])"
    },
    {
     "expr": "rate(chaincode_launch_failures[5m])"
    },
    {
     "expr": "rate(chaincode_launch_timeouts[5m])"
    },
    {
     "expr": "rate(chaincode_shim_requests_completed[5m])"
    },
    {
     "expr": "rate(chaincode_shim_requests_received[5m])"
    }
   ]
  },
  {
   "title": "chaincode_launch_duration",
   "type": "heatmap",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 39 },
   "targets": [
    {
     "expr": "chaincode_launch_duration_bucket",
     "legendFormat": "{{le}}"
    }
   ]
  },
  {
   "title": "chaincode_shim_request_duration_bucket",
   "type": "heatmap",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 39 },
   "targets": [
    {
     "expr": "chaincode_shim_request_duration_bucket",
     "legendFormat": "{{le}}"
    }
   ]
  },
  { "title": "Endorsement", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 47 } },
  {
   "title": "endorser",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 48 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "rate(endorser_chaincode_instantiation_failures[5m])"
    },
    {
     "expr": "rate(endorser_duplicate_transaction_failures[5m])"
    },
    {
     "expr": "rate(endorser_endorsement_failures[5m])"
    },
    {
     "expr": "rate(endorser_proposal_acl_failures[5m])"
    },
    {
     "expr": "rate(endorser_proposal_simulation_failures[5m])"
    },
    {
     "expr": "rate(endorser_proposal_validation_failures[5m])"
    },
    {
     "expr": "rate(endorser_proposals_received[5m])"
    },
    {
     "expr": "rate(endorser_successful_proposals[5m])"
    }
   ]
  },
  {
   "title": "endorser_proposal_duration",
   "type": "heatmap",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 48 },
   "targets": [
    {
     "expr": "endorser_proposal_duration_bucket",
     "legendFormat": "{{le}}"
    }
   ]
  },
  { "title": "Ledger", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 56 } },
  {
   "title": "couchdb_processing_time",
   "type": "heatmap",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 57 },
   "targets": [
    {
     "expr": "histogram_quantile(0.95, sum(rate(couchdb_processing_time_bucket[5m])) by (le))"
    }
   ]
  },
  {
   "title": "ledger_block_processing_time",
   "type": "heatmap",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 65 },
   "targets": [
    {
     "expr": "ledger_block_processing_time_bucket",
     "legendFormat": "{{le}}"
    }
   ]
  },
  {
   "title": "ledger_blockstorage_and_pvtdata_commit_time",
   "type": "heatmap",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 65 },
   "targets": [
    {
     "expr": "ledger_blockstorage_and_pvtdata_commit_time_bucket",
     "legendFormat": "{{le}}"
    }
   ]
  },
  {
   "title": "ledgerledger_blockstorage_and_pvtdata_commit_time",
   "type": "heatmap",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 73 },
   "targets": [
    {
     "expr": "ledger_blockstorage_and_pvtdata_commit_time_bucket",
     "legendFormat": "{{le}}"
    }
   ]
  },
  {
   "title": "ledger_statedb_commit_time",
   "type": "heatmap",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 73 },
   "targets": [
    {
     "expr": "ledger_statedb_commit_time_bucket",
     "legendFormat": "{{le}}"
    }
   ]
  },
  { "title": "Gossip", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 81 } },
  {
   "title": "gossip",
   "type": "graph",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 82 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "rate(gossip_comm_messages_received[5m])"
    },
    {
     "expr": "rate(gossip_comm_messages_sent[5m])"
    },
    {
     "expr": "rate(gossip_comm_overflow_count[5m])"
    }
   ]
  },
  {
   "title": "gossip_privdata_commit_block_duration",
   "type": "heatmap",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 91 },
   "targets": [
    {
     "expr": "gossip_privdata_commit_block_duration_bucket",
     "legendFormat": "{{le}}"
    }
   ]
  },
  {
   "title": "gossip_privdata_fetch_duration",
   "type": "heatmap",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 91 },
   "targets": [
    {
     "expr": "gossip_privdata_fetch_duration_bucket",
     "legendFormat": "{{le}}"
    }
   ]
  },
  {
   "title": "gossip_privdata_list_missing_duration",
   "type": "heatmap",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 100 },
   "targets": [
    {
     "expr": "gossip_privdata_list_missing_duration_bucket",
     "legendFormat": "{{le}}"
    }
   ]
  },
  {
   "title": "gossip_privdata_pull_duration",
   "type": "heatmap",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 100 },
   "targets": [
    {
     "expr": "gossip_privdata_pull_duration_bucket",
     "legendFormat": "{{le}}"
    }
   ]
  },
  {
   "title": "gossip_privdata_purge_duration",
   "type": "heatmap",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 109 },
   "targets": [
    {
     "expr": "gossip_privdata_purge_duration_bucket",
     "legendFormat": "{{le}}"
    }
   ]
  },
  {
   "title": "gossip_privdata_reconciliation_duration",
   "type": "heatmap",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 109 },
   "targets": [
    {
     "expr": "gossip_privdata_reconciliation_duration_bucket",
     "legendFormat": "{{le}}"
    }
   ]
  },
  {
   "title": "gossip_privdata_retrieve_duration",
   "type": "heatmap",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 118 },
   "targets": [
    {
     "expr": "gossip_privdata_retrieve_duration_bucket",
     "legendFormat": "{{le}}"
    }
   ]
  },
  {
   "title": "gossip_privdata_send_duration",
   "type": "heatmap",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 118 },
   "targets": [
    {
     "expr": "gossip_privdata_send_duration_bucket",
     "legendFormat": "{{le}}"
    }
   ]
  },
  {
   "title": "gossip_privdata_validation_duration",
   "type": "heatmap",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 127 },
   "targets": [
    {
     "expr": "gossip_privdata_validation_duration_bucket",
     "legendFormat": "{{le}}"
    }
   ]
  },
  {
   "title": "gossip_state_commit_duration",
   "type": "heatmap",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 127 },
   "targets": [
    {
     "expr": "gossip_state_commit_duration_bucket",
     "legendFormat": "{{le}}"
    }
   ]
  }
 ]
}