{
 "title": "Hyperledger Fabric Common Dash Board",
 "time": { "from": "2021-03-27T10:24:01.867Z", "to": "2021-03-27T10:53:49.262Z" },
 "panels": [
  {
   "title": "Basic",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 },
   "collapsed": true,
   "panels": [
    {
     "title": "Live Monitored Nodes",
     "type": "table",
     "gridPos": { "h": 5, "w": 24, "x": 0, "y": 1 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      { "expr": "fabric_version" }
     ]
    }
   ]
  },
  {
   "title": "Blocks",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 1 },
   "collapsed": true,
   "panels": [
    {
     "title": "ledger_blockchain_height_rate",
     "type": "graph",
     "gridPos": { "h": 11, "w": 12, "x": 0, "y": 2 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "rate(ledger_blockchain_height[1m])"
      }
     ]
    },
    {
     "title": "ledger_blockchain_height",
     "type": "gauge",
     "gridPos": { "h": 11, "w": 12, "x": 12, "y": 2 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "sum(ledger_blockchain_height) by (channel,job)",
       "legendFormat": "{{channel}} {{job}}"
      }
     ]
    },
    {
     "title": "Block procesing time",
     "type": "heatmap",
     "gridPos": { "h": 8, "w": 24, "x": 0, "y": 13 },
     "targets": [
      {
       "expr": "ledger_block_processing_time_bucket\n",
       "legendFormat": "{{le}}"
      }
     ]
    },
    {
     "title": "Rate of business transactions per channel",
     "type": "graph",
     "gridPos": { "h": 9, "w": 12, "x": 0, "y": 21 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "sum(rate(ledger_transaction_count{transaction_type=\"ENDORSER_TRANSACTION\"}[1m])) by (channel)"
      }
     ]
    },
    {
     "title": "Sum of business transactions per channel",
     "type": "gauge",
     "gridPos": { "h": 9, "w": 12, "x": 12, "y": 21 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "sum(ledger_transaction_count{transaction_type=\"ENDORSER_TRANSACTION\"}) by (channel,job)"
      }
     ]
    }
   ]
  },
  {
   "title": "GRPC Connection",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 2 },
   "collapsed": true,
   "panels": [
    {
     "title": "grpc_server_stream_request_duration",
     "type": "heatmap",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 3 },
     "targets": [
      {
       "expr": "grpc_server_stream_request_duration_bucket",
       "legendFormat": "{{le}}"
      }
     ]
    },
    {
     "title": "grpc_server_unary_request_duration",
     "type": "heatmap",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 3 },
     "targets": [
      {
       "expr": "grpc_server_unary_request_duration_bucket",
       "legendFormat": "{{le}}"
      }
     ]
    },
    {
     "title": "GRPC Connections",
     "type": "graph",
     "gridPos": { "h": 9, "w": 12, "x": 0, "y": 11 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "rate(grpc_comm_conn_closed[5m])"
      },
      {
       "expr": "rate(grpc_comm_conn_opened[5m])"
      },
      {
       "expr": "rate(grpc_server_stream_messages_received[5m])"
      },
      {
       "expr": "rate(grpc_server_stream_messages_sent[5m])"
      },
      {
       "expr": "rate(grpc_server_stream_requests_completed[5m])"
      },
      {
       "expr": "rate(grpc_server_stream_requests_received[5m])"
      },
      {
       "expr": "rate(grpc_server_unary_requests_completed[5m])"
      },
      {
       "expr": "rate(grpc_server_unary_requests_received[5m])"
      }
     ]
    },
    {
     "title": "GRPC Connections RealTime",
     "type": "table",
     "gridPos": { "h": 9, "w": 12, "x": 12, "y": 11 },
     "targets": [
      { "expr": "grpc_comm_conn_closed" },
      { "expr": "grpc_comm_conn_opened" },
      {
       "expr": "grpc_server_stream_messages_received"
      },
      {
       "expr": "grpc_server_stream_messages_sent"
      },
      {
       "expr": "grpc_server_stream_requests_completed"
      },
      {
       "expr": "grpc_server_stream_requests_received"
      },
      {
       "expr": "grpc_server_unary_requests_completed"
      },
      {
       "expr": "grpc_server_unary_requests_received"
      }
     ]
    }
   ]
  },
  {
   "title": "Logging",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 3 },
   "collapsed": true,
   "panels": [
    {
     "title": "logging rate",
     "type": "graph",
     "gridPos": { "h": 7, "w": 24, "x": 0, "y": 4 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "rate(logging_entries_checked[5m])"
      },
      {
       "expr": "rate(logging_entries_written[5m])"
      }
     ]
    }
   ]
  }
 ]
}